### ISSUE TITLE
nodemon not in a package

### ISSUE THREAD

**Issue by Shresthaprakash75** [nathanlippi/team-habits-slackbot#1]
this issue is shown on npm start after npm install

![Screenshot from 2021-05-03 18-12-50](https://user-images.githubusercontent.com/31161376/116875889-5c81f200-ac3b-11eb-97b1-5ef258a0b6fc.png)

this issue can be solved with npm install nodemon

**Comment by nathanlippi** [comment]
@Shresthaprakash75 - Thanks! The guide I used recommended installing nodemon globally using "npm install -g nodemon", so it shouldn't be in the package. I'll add it to README.md.

**Comment by nathanlippi** [comment]
Updated the README.md!

**Comment by Shresthaprakash75** [comment]
cool
